# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blinky}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Perryn Fowler"]
  s.date = %q{2010-11-14}
  s.default_executable = %q{blinky}
  s.description = %q{plug and play support for USB build status indicators}
  s.email = %q{perryn.fowler@gmail.com}
  s.executables = ["blinky"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/blinky",
     "device_recipes/delcom_engineering/model_804005.rb",
     "device_recipes/recipes.rb",
     "lib/blinky.rb",
     "lib/blinky/no_supported_devices_found.rb",
     "notes.txt",
     "spec/blinky_spec.rb",
     "spec/fixtures/device_recipes/aenima_engineering/462.rb",
     "spec/fixtures/device_recipes/fragile_engineering/wretched.rb",
     "spec/fixtures/device_recipes/recipes.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/perryn/blinky}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{helps you see the light}
  s.test_files = [
    "spec/blinky_spec.rb",
     "spec/fixtures/device_recipes/aenima_engineering/462.rb",
     "spec/fixtures/device_recipes/fragile_engineering/wretched.rb",
     "spec/fixtures/device_recipes/recipes.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-usb>, [">= 0.2.1"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<ruby-usb>, [">= 0.2.1"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby-usb>, [">= 0.2.1"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

